name: build-and-push
on:
  push:
    branches:
      - main
jobs:
  cargo-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
      - name: test
        run: cargo test --target x86_64-unknown-linux-gnu
  cargo-build:
    name: Build cargo
    needs: cargo-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup target
        run: |
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: cargo build
        run: cargo build --release --target aarch64-unknown-linux-gnu
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rust_practice
          path: target/aarch64-unknown-linux-gnu/release/rust_practice
  docker-build-and-push-image:
    name: Build and Push Docker Image
    needs: cargo-build
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: rust_practice
          path: target/aarch64-unknown-linux-gnu/release/
      - run: |
          ls .
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: 926972041025.dkr.ecr.ap-northeast-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64
          tags: 926972041025.dkr.ecr.ap-northeast-1.amazonaws.com/rust-practice:${{ github.sha }}

